name: ci/cd

on:
  push:
    branches: [ci-test]
  pull_request:
    branches: [ci-test]

  jobs:
    build:
      name: Build on OpenJDK ${{ matrix.jdk_version }} / ${{ matrix.os }}
      runs-on: ubuntu-latest

      strategy:
        matrix:
          # JDK LTS: 8, 11, 17
          jdk_version: [8, 11, 15, 16]
          os: [ubuntu-latest]

      container:
        image: clojure:openjdk-${{ matrix.jdk_version }}-tools-deps

      deps:
        - uses: action/checkout@v2
        - name: Test
          run: ./bin/kaocha
